### ISSUE TITLE
ID vs UUID

### ISSUE THREAD

**Issue by wrabit** [specialtactics/laravel-api-boilerplate#14]
More a question than a bug, I am eyeing up your solution to migrate to from my current API setup.

I currently use a sequential ID for each entity and currently request a row using that and an organisation id.

i.e. tbl systems:

```
id INT auto inc PRIMARY
seq INT
organisation_id INT
name VARCHAR
......
```

I do this so the org has their own 1 based, scoped id's for each entity and I'm using this in the url like `systems/1`.

I notice this implementation uses UUID, could you let me know what your recommended approach is for my use case?

**Comment by specialtactics** [comment]
Hi @williamabbott 

It's not completely clear to me what the issue is from what you've said (maybe you can post more of your schema and queries). But by the sounds of it, it seems like a system managing entitites, where you want to segregate them in all cases by this org ID.

In this case, I think it would be fine if you were to just replace both the id of the entity and the org with UUIDs, and maintain your current approach without any changes.

Let me know if you need any further help :)

**Comment by wrabit** [comment]
Thanks ok so I have many entities including Process, System, Risk, etc. This is an example table.

```
+----+--------+-----+-----------------------------+
| id | org_id | seq |            name             |
+----+--------+-----+-----------------------------+
|  1 |      1 |   1 | process 1                   |
|  2 |      1 |   2 | another process             |
|  3 |      1 |   3 | yep you got it              |
|  4 |      2 |   1 | im a process from other org |
+----+--------+-----+-----------------------------+
```

The seq number is used in urls for entities and acts as the public id to the org in their admin views. It also helps with default ordering of rows in their admin tables.

At the moment on the backed I am grabbing the entity based on an api query i.e. `GET api/process/1` and would do this by (simplified)

`SELECT id, name FROM processes WHERE seq = $get['seq'] AND org_id = $jwt['org_id']`

I see that 'out of the box' your implementation deals with uuid and I just wondered if there was a recommended approach if we wanted to swap out the uuid functionality with this? extend the base classes ourselves?

**Comment by specialtactics** [comment]
@williamabbott 

If you mean to actually use auto-increment IDs with this boilerplate, I would not recommend that.

In theory, I think it would be as easy as changing the $incrementing attribute of the model to true and $keyType to int, and then you should get what you want. You can do this in the BaseModel class. However I am not sure what other repercussions it will have, but you can give that a go and see how far it takes you - I'm happy to offer you advice if you run into any issues.

The reason I don't recommend it, is that it is not good practise for APIs to use incrementing integers (or any integers) for identifiers, let alone make them public to the API consumers. A quick google will get you many reasons for why this is the case.

What I would do if I were you is to do a once-over where you change add a UUID key column for every ID column, and then another script afterwards to link everything based on existing IDs. You can then use the UUIDs in URLs much the same way, and still use them in queries - theoretically nothing should change functionality wise.

All you would have to do is run a migration to create mirror UUID keys for every ID key, and switch the primary keys of your models to use the UUID instead of the old ID. Then you can use the old ID for ordering still if you want to. In theory, this shouldn't be too hard, as it's a very systematic approach.

**Comment by wrabit** [comment]
@specialtactics I would like to keep a simple numbering system for org's entities so they are easily referenceable online or offline. It's not the table's primary key, just a sequential number scoped to the entity and the organisation. For consistency I am using this in the url when they are on the front end. Also, I am currently using this sequential number for api calls but always doing so with their org_id so we reference the correct row.

With your proposal will the uuid be used internally as well for joins and such? Are there any concerns for performance this way?

Maybe a compromise in my case, between best practise and maintaining a simple numbering system would be:

- Convert to using UUID's as you describe
- Continue to manage the sequential numbering but stop using it for api calls
- Move to using UUID's in urls for the web app and for api calls

And a final point - it's fine to be exposing the UUID primary key publically? 

(thanks for the help)

**Comment by specialtactics** [comment]
Hi @williamabbott - that sounds like a good way to go.

> With your proposal will the uuid be used internally as well for joins and such? Are there any concerns for performance this way?

Correct.

Performance wise, not a big deal. It is slower, but it is not a noticable difference until you get into hundreds of millions of records. Of course the mileage you get does depend on your use cases and queries, but if you are doing just lookups by the primary key, it will make no real difference.

One note is that PostgreSQL is more efficient than MySQL/MariaDB because it has a binary UUID field type. I wouldn't change your DB engine mid-project or anything, but it may be relevant for future considerations :)

> And a final point - it's fine to be exposing the UUID primary key publically?

Totally fine - this is quite common practise in fact, you probably use some websites which do this already without realising it in fact. It is certainly much better than exposing incrementing IDs (because in that scenario anyone can guess what the next or previous one will be very easily).

Usually when exposing unique identifiers to users you will want to use either a UUID, or perhaps some kind of a human readable "slug" (which you will then need to manage the uniqueness of), if you want users to be able to read and remember it.
