### ISSUE TITLE
Deployment of laravel-api-boilerplate

### ISSUE THREAD

**Issue by Eolykab** [specialtactics/laravel-api-boilerplate#45]
This is not a feature request. I just want to know the best option to deploy this project.

**Comment by specialtactics** [comment]
Hey

Well, there is nothing special about this boilerplate - infrastructure wise, the answer would be the same for how to deploy any Laravel application or just about any PHP project. And this will depend on the scale of your project and the amount of time and money you want to put into the infrastructure, etc.

I have many different deployment schemes across both personal and professional projects, but I would recommend you google "laravel deployment" or something like that, you will get many suggestions - because there are a million ways to do it, and largely depends on your personal preferences and time vs money equation.
